sudo: required
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "build-tools;29.0.2"
  - export LANG=en_US.UTF-8

script:
  - ./gradlew clean
  - ./gradlew org.eclipse.paho.android.sample:assemble BasicExample:assemble
  - ./gradlew org.eclipse.paho.android.service:assemble


